# Run using:
#   docker compose up --build

services:
  filebrowser:
    container_name: filebrowser
    build:
      dockerfile: Dockerfile
      context: .
    networks:
      - filebrowser
    ports:
      - 8000:80
    volumes:
      - filebrowser:/flux/vault

networks:
  filebrowser:

volumes:
  filebrowser:
